#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	neogit="/usr/bin/nvim -c Neogit" \
	ngit="neogit" \
  nv="neovide" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \

# dotnet
alias \
	dnb="dotnet build" \
	dnr="dotnet run" \
	dnw="dotnet watch" \
	dnwr="dotnet watch run" \
	dnres="dotnet restore" \
	dnefdu="dotnet ef database update" \
	dnefdd="dotnet ef database drop" \
	dnefmr="dotnet ef migrations remove"

# exa
alias \
	ls='exa --icons --group-directories-first' \
	l='exa -lbF --git --icons --group-directories-first' \
	ll='exa -lbGF --git --icons --group-directories-first'  \
	llm='exa -lbGd --git --sort=modified --icons --group-directories-first'    \
	la='exa -labhUmu --time-style=iso --git --color-scale --icons --group-directories-first'   \
	lx='exa -lbhHigUmuSa@ --time-style=long-iso --git --color-scale --icons --group-directories-first'  \
	lt='exa --long --tree --level=3 --git --color-scale --icons'

# configs bare repo
alias cfg="git --git-dir=$HOME/.dotFiles --work-tree=$HOME"

