#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Set DPI. User may want to use a larger number for larger screens.
xrandr --output DisplayPort-0 --set TearFree on --dpi 96
setbg &			# set the background with the `setbg` script
kmonad ~/.config/config.kbd &
wpch &

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

# optout dotnet telemetry
export DOTNET_CLI_TELEMETRY_OUTPUT=1

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
dbus-update-activation-environment --systemd DISPLAY

autostart="mpd xcompmgr dunst unclutter pipewire remapd pcloud flameshot"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
