#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
kmonad ~/.config/config.kbd &
pcloud &

# optout dotnet telemetry
export DOTNET_CLI_TELEMETRY_OUTPUT=1

# Fix issue with dbus and gnome-keyring
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
dbus-update-activation-environment --systemd DISPLAY

autostart="mpd xcompmgr dunst unclutter pipewire"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
