[font]
# normal = { family = "MonoLisaScript Nerd Font" }
# normal = { family = "Iosevka SS08" }
normal = { family = "Iosevka" }
size = 12
# offset = { x = 0, y = -1 }

[window]
decorations_theme_variant = "Dark"
opacity = 0.9
